"""note progress: read marks

Revision ID: 9c60e8ca839c
Revises: a42fa0bd8246
Create Date: 2026-08-07 20:03:46.822806

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# идентификаторы ревизии, используемые Alembic.
revision: str = '9c60e8ca839c'
down_revision: str | None = 'a42fa0bd8246'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['theory_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_progress_is_read'), 'note_progress', ['is_read'], unique=False)
    op.create_index(op.f('ix_note_progress_note_id'), 'note_progress', ['note_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_progress_note_id'), table_name='note_progress')
    op.drop_index(op.f('ix_note_progress_is_read'), table_name='note_progress')
    op.drop_table('note_progress')
    # ### end Alembic commands ###
