"""initial schema: content and personal tables

Revision ID: a42fa0bd8246
Revises: 
Create Date: 2026-08-02 14:00:48.984405

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# идентификаторы ревизии, используемые Alembic.
revision: str = 'a42fa0bd8246'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_slug'), 'blocks', ['slug'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('schema_sql', sa.Text(), nullable=False),
    sa.Column('seed_sql', sa.Text(), nullable=False),
    sa.Column('er_description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_slug'), 'datasets', ['slug'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'slug', name='uq_topics_block_slug')
    )
    op.create_index(op.f('ix_topics_block_id'), 'topics', ['block_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('solution_md', sa.Text(), nullable=True),
    sa.Column('explanation_md', sa.Text(), nullable=True),
    sa.Column('solution_sql', sa.Text(), nullable=True),
    sa.Column('check_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_tasks_difficulty'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_block_id'), 'tasks', ['block_id'], unique=False)
    op.create_index(op.f('ix_tasks_difficulty'), 'tasks', ['difficulty'], unique=False)
    op.create_index(op.f('ix_tasks_is_archived'), 'tasks', ['is_archived'], unique=False)
    op.create_index(op.f('ix_tasks_slug'), 'tasks', ['slug'], unique=True)
    op.create_index(op.f('ix_tasks_topic_id'), 'tasks', ['topic_id'], unique=False)
    op.create_table('theory_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theory_notes_block_id'), 'theory_notes', ['block_id'], unique=False)
    op.create_index(op.f('ix_theory_notes_slug'), 'theory_notes', ['slug'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_created_at'), 'attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_attempts_task_id'), 'attempts', ['task_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('question_md', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['theory_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_block_id'), 'cards', ['block_id'], unique=False)
    op.create_index(op.f('ix_cards_is_archived'), 'cards', ['is_archived'], unique=False)
    op.create_index(op.f('ix_cards_slug'), 'cards', ['slug'], unique=True)
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('first_solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personal_note_md', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'solved', 'failed')", name='ck_task_progress_status'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_status'), 'task_progress', ['status'], unique=False)
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=True)
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_card_id'), 'review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_reviewed_at'), 'review_logs', ['reviewed_at'], unique=False)
    op.create_table('review_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('last_grade', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_states_card_id'), 'review_states', ['card_id'], unique=True)
    op.create_index(op.f('ix_review_states_due_date'), 'review_states', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_states_due_date'), table_name='review_states')
    op.drop_index(op.f('ix_review_states_card_id'), table_name='review_states')
    op.drop_table('review_states')
    op.drop_index(op.f('ix_review_logs_reviewed_at'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_card_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_status'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index(op.f('ix_cards_slug'), table_name='cards')
    op.drop_index(op.f('ix_cards_is_archived'), table_name='cards')
    op.drop_index(op.f('ix_cards_block_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_attempts_task_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_created_at'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_theory_notes_slug'), table_name='theory_notes')
    op.drop_index(op.f('ix_theory_notes_block_id'), table_name='theory_notes')
    op.drop_table('theory_notes')
    op.drop_index(op.f('ix_tasks_topic_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_slug'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_archived'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_difficulty'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_block_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_topics_block_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_datasets_slug'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_blocks_slug'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
